### ISSUE TITLE
Python Implementation

### ISSUE THREAD

**Issue by Avv22** [cran/ICSOutlier#1]
Hello Cran,

Is there Python implementation for Invariant coordinate selection?  Can we work together to write Python implementation?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!

**Comment by Avv22** [comment]
@gaborcsardi . I can not find a package for Python, is there any solution that you would recommend, please?
